/**
 * GENERATED — do not edit.
 *
 * Built by `prisma/scripts/build-city-catalog.ts` from
 * `prisma/content/colleges.json`. Re-run that script to refresh it.
 *
 * 985 places, 35 states.
 */

/** `[city, state]`, busiest first. */
export const CITY_STATE_PAIRS: readonly (readonly [string, string])[] = [
  ["Bangalore", "Karnataka"],
  ["Pune", "Maharashtra"],
  ["Hyderabad", "Telangana"],
  ["Jaipur", "Rajasthan"],
  ["Bhopal", "Madhya Pradesh"],
  ["Nagpur", "Maharashtra"],
  ["Chennai", "Tamil Nadu"],
  ["Mumbai", "Maharashtra"],
  ["Indore", "Madhya Pradesh"],
  ["Lucknow", "Uttar Pradesh"],
  ["Allahabad", "Uttar Pradesh"],
  ["Coimbatore", "Tamil Nadu"],
  ["Kolkata", "West Bengal"],
  ["Guntur", "Andhra Pradesh"],
  ["Gulbarga", "Karnataka"],
  ["Meerut", "Uttar Pradesh"],
  ["Nashik", "Maharashtra"],
  ["Chittoor", "Andhra Pradesh"],
  ["Belgaum", "Karnataka"],
  ["Visakhapatnam", "Andhra Pradesh"],
  ["Aurangabad", "Maharashtra"],
  ["Rangareddy", "Telangana"],
  ["Khordha", "Odisha"],
  ["Varanasi", "Uttar Pradesh"],
  ["Thane", "Maharashtra"],
  ["Rajkot", "Gujarat"],
  ["Mysore", "Karnataka"],
  ["Ernakulam", "Kerala"],
  ["Sikar", "Rajasthan"],
  ["Dakshina Kannada", "Karnataka"],
  ["Gwalior", "Madhya Pradesh"],
  ["East Godavari", "Andhra Pradesh"],
  ["Jabalpur", "Madhya Pradesh"],
  ["Ahmadabad", "Gujarat"],
  ["Ghaziabad", "Uttar Pradesh"],
  ["Kolhapur", "Maharashtra"],
  ["Dharwad", "Karnataka"],
  ["Gorakhpur", "Uttar Pradesh"],
  ["Azamgarh", "Uttar Pradesh"],
  ["Patna", "Bihar"],
  ["Raipur", "Chhattisgarh"],
  ["Krishna", "Andhra Pradesh"],
  ["Jaunpur", "Uttar Pradesh"],
  ["Agra", "Uttar Pradesh"],
  ["Anantapur", "Andhra Pradesh"],
  ["Prakasam", "Andhra Pradesh"],
  ["Salem", "Tamil Nadu"],
  ["Solapur", "Maharashtra"],
  ["Thiruvananthapuram", "Kerala"],
  ["Warangal", "Telangana"],
  ["Bidar", "Karnataka"],
  ["Tumkur", "Karnataka"],
  ["Kanpur Nagar", "Uttar Pradesh"],
  ["Surat", "Gujarat"],
  ["Nalgonda", "Telangana"],
  ["Vellore", "Tamil Nadu"],
  ["Ghazipur", "Uttar Pradesh"],
  ["Kurnool", "Andhra Pradesh"],
  ["Tiruchirappalli", "Tamil Nadu"],
  ["Madurai", "Tamil Nadu"],
  ["Karimnagar", "Telangana"],
  ["Kozhikode", "Kerala"],
  ["Anand", "Gujarat"],
  ["Thrissur", "Kerala"],
  ["Dehradun", "Uttarakhand"],
  ["Namakkal", "Tamil Nadu"],
  ["Jalgaon", "Maharashtra"],
  ["Malappuram", "Kerala"],
  ["Y.s.r.", "Andhra Pradesh"],
  ["Faizabad", "Uttar Pradesh"],
  ["Latur", "Maharashtra"],
  ["Alwar", "Rajasthan"],
  ["West Godavari", "Andhra Pradesh"],
  ["Bijapur", "Karnataka"],
  ["Tirunelveli", "Tamil Nadu"],
  ["Ahmadnagar", "Maharashtra"],
  ["Pratapgarh", "Uttar Pradesh"],
  ["Satara", "Maharashtra"],
  ["Kottayam", "Kerala"],
  ["Mathura", "Uttar Pradesh"],
  ["Durg", "Chhattisgarh"],
  ["Chandrapur", "Maharashtra"],
  ["Sangli", "Maharashtra"],
  ["Deoria", "Uttar Pradesh"],
  ["Ludhiana", "Punjab"],
  ["Gandhinagar", "Gujarat"],
  ["Jodhpur", "Rajasthan"],
  ["Nanded", "Maharashtra"],
  ["Ahmedabad", "Gujarat"],
  ["Kollam", "Kerala"],
  ["Mau", "Uttar Pradesh"],
  ["Cuttack", "Odisha"],
  ["Raichur", "Karnataka"],
  ["Ballia", "Uttar Pradesh"],
  ["Khammam", "Telangana"],
  ["Thanjavur", "Tamil Nadu"],
  ["Srikakulam", "Andhra Pradesh"],
  ["Sri Potti Sriramulu Nellore", "Andhra Pradesh"],
  ["Bhubaneswar", "Odisha"],
  ["Udaipur", "Rajasthan"],
  ["Bilaspur", "Chhattisgarh"],
  ["Vizianagaram", "Andhra Pradesh"],
  ["Kannur", "Kerala"],
  ["Mumbai Suburban", "Maharashtra"],
  ["Patiala", "Punjab"],
  ["Amravati", "Maharashtra"],
  ["Hardoi", "Uttar Pradesh"],
  ["Palakkad", "Kerala"],
  ["Sultanpur", "Uttar Pradesh"],
  ["Bareilly", "Uttar Pradesh"],
  ["Junagadh", "Gujarat"],
  ["Kancheepuram", "Tamil Nadu"],
  ["Dhule", "Maharashtra"],
  ["Erode", "Tamil Nadu"],
  ["Gautam Buddha Nagar", "Uttar Pradesh"],
  ["Jalandhar", "Punjab"],
  ["Kolar", "Karnataka"],
  ["Hassan", "Karnataka"],
  ["Medak", "Telangana"],
  ["Jhunjhunun", "Rajasthan"],
  ["Saharanpur", "Uttar Pradesh"],
  ["Vadodara", "Gujarat"],
  ["Bagalkot", "Karnataka"],
  ["Shimoga", "Karnataka"],
  ["Bhavnagar", "Gujarat"],
  ["Mahesana", "Gujarat"],
  ["Dindigul", "Tamil Nadu"],
  ["Jammu", "Jammu & Kashmir"],
  ["Pudukkottai", "Tamil Nadu"],
  ["Udupi", "Karnataka"],
  ["Tiruvannamalai", "Tamil Nadu"],
  ["Aligarh", "Uttar Pradesh"],
  ["Amritsar", "Punjab"],
  ["Rohtak", "Haryana"],
  ["Bellary", "Karnataka"],
  ["Nizamabad", "Telangana"],
  ["Kota", "Rajasthan"],
  ["Wardha", "Maharashtra"],
  ["Dharmapuri", "Tamil Nadu"],
  ["Rewa", "Madhya Pradesh"],
  ["Bathinda", "Punjab"],
  ["Cuddalore", "Tamil Nadu"],
  ["Thiruvallur", "Tamil Nadu"],
  ["Parbhani", "Maharashtra"],
  ["North Twenty Four Parganas", "West Bengal"],
  ["Barddhaman", "West Bengal"],
  ["Chitradurga", "Karnataka"],
  ["Ujjain", "Madhya Pradesh"],
  ["Gadag", "Karnataka"],
  ["Ambedkar Nagar", "Uttar Pradesh"],
  ["Ganjam", "Odisha"],
  ["Ranchi", "Jharkhand"],
  ["Sabar Kantha", "Gujarat"],
  ["Ajmer", "Rajasthan"],
  ["Sitapur", "Uttar Pradesh"],
  ["Kanniyakumari", "Tamil Nadu"],
  ["Mandya", "Karnataka"],
  ["Davanagere", "Karnataka"],
  ["Mangalore", "Karnataka"],
  ["Bharatpur", "Rajasthan"],
  ["New Delhi", "Delhi"],
  ["Bid", "Maharashtra"],
  ["Mahbubnagar", "Telangana"],
  ["Adilabad", "Telangana"],
  ["Faridabad", "Haryana"],
  ["Sangrur", "Punjab"],
  ["Gurdaspur", "Punjab"],
  ["Satna", "Madhya Pradesh"],
  ["Moradabad", "Uttar Pradesh"],
  ["Yavatmal", "Maharashtra"],
  ["Murshidabad", "West Bengal"],
  ["Gurgaon", "Haryana"],
  ["Gonda", "Uttar Pradesh"],
  ["Mirzapur", "Uttar Pradesh"],
  ["Sagar", "Madhya Pradesh"],
  ["Kanpur Dehat", "Uttar Pradesh"],
  ["Raigarh", "Maharashtra"],
  ["Unnao", "Uttar Pradesh"],
  ["Puducherry", "Puducherry"],
  ["Bangalore Rural", "Karnataka"],
  ["Etawah", "Uttar Pradesh"],
  ["Firozabad", "Uttar Pradesh"],
  ["Pathanamthitta", "Kerala"],
  ["Alappuzha", "Kerala"],
  ["Fatehpur", "Uttar Pradesh"],
  ["Kangra", "Himachal Pradesh"],
  ["Kaushambi", "Uttar Pradesh"],
  ["Jhajjar", "Haryana"],
  ["Uttara Kannada", "Karnataka"],
  ["Hanumangarh", "Rajasthan"],
  ["Ganganagar", "Rajasthan"],
  ["Farrukhabad", "Uttar Pradesh"],
  ["Gadchiroli", "Maharashtra"],
  ["Nagapattinam", "Tamil Nadu"],
  ["Muzaffarnagar", "Uttar Pradesh"],
  ["Muzaffarpur", "Bihar"],
  ["Jalna", "Maharashtra"],
  ["Viluppuram", "Tamil Nadu"],
  ["Bijnor", "Uttar Pradesh"],
  ["Guwahati", "Assam"],
  ["Puri", "Odisha"],
  ["Ratnagiri", "Maharashtra"],
  ["Bhind", "Madhya Pradesh"],
  ["Bikaner", "Rajasthan"],
  ["Moga", "Punjab"],
  ["Sonipat", "Haryana"],
  ["Jhansi", "Uttar Pradesh"],
  ["Nellore", "Andhra Pradesh"],
  ["Osmanabad", "Maharashtra"],
  ["Baleshwar", "Odisha"],
  ["Churu", "Rajasthan"],
  ["Patan", "Gujarat"],
  ["Etah", "Uttar Pradesh"],
  ["Hoshiarpur", "Punjab"],
  ["Mainpuri", "Uttar Pradesh"],
  ["Akola", "Maharashtra"],
  ["Basti", "Uttar Pradesh"],
  ["Kamrup", "Assam"],
  ["Kadapa", "Andhra Pradesh"],
  ["Virudhunagar", "Tamil Nadu"],
  ["Darbhanga", "Bihar"],
  ["Delhi", "Delhi"],
  ["Jamnagar", "Gujarat"],
  ["Srinagar", "Jammu & Kashmir"],
  ["Auraiya", "Uttar Pradesh"],
  ["Nagaur", "Rajasthan"],
  ["Kannauj", "Uttar Pradesh"],
  ["Koppal", "Karnataka"],
  ["Idukki", "Kerala"],
  ["Jalaun", "Uttar Pradesh"],
  ["Mandi", "Himachal Pradesh"],
  ["South Twenty Four Parganas", "West Bengal"],
  ["Amreli", "Gujarat"],
  ["Bhandara", "Maharashtra"],
  ["Balaghat", "Madhya Pradesh"],
  ["Buldana", "Maharashtra"],
  ["Hisar", "Haryana"],
  ["Karnal", "Haryana"],
  ["Betul", "Madhya Pradesh"],
  ["Haveri", "Karnataka"],
  ["Nadia", "West Bengal"],
  ["Perambalur", "Tamil Nadu"],
  ["Shimla", "Himachal Pradesh"],
  ["Tonk", "Rajasthan"],
  ["Chhatarpur", "Madhya Pradesh"],
  ["Dausa", "Rajasthan"],
  ["Sahibzada Ajit Singh Nagar", "Punjab"],
  ["Tirupati", "Andhra Pradesh"],
  ["Chandigarh", "Chandigarh"],
  ["Nandurbar", "Maharashtra"],
  ["Solan", "Himachal Pradesh"],
  ["Bhiwani", "Haryana"],
  ["Morena", "Madhya Pradesh"],
  ["Vidisha", "Madhya Pradesh"],
  ["Kanpur", "Uttar Pradesh"],
  ["Kasaragod", "Kerala"],
  ["Sivaganga", "Tamil Nadu"],
  ["Banda", "Uttar Pradesh"],
  ["Vijayawada", "Andhra Pradesh"],
  ["Tiruppur", "Tamil Nadu"],
  ["Bankura", "West Bengal"],
  ["Chhindwara", "Madhya Pradesh"],
  ["Hardwar", "Uttarakhand"],
  ["Ramanagara", "Karnataka"],
  ["Sirsa", "Haryana"],
  ["Sundargarh", "Odisha"],
  ["Krishnagiri", "Tamil Nadu"],
  ["Rae Bareli", "Uttar Pradesh"],
  ["Rohtas", "Bihar"],
  ["Banswara", "Rajasthan"],
  ["Bhadrak", "Odisha"],
  ["Chandauli", "Uttar Pradesh"],
  ["Mayurbhanj", "Odisha"],
  ["Ambala", "Haryana"],
  ["Dhanbad", "Jharkhand"],
  ["Rajnandgaon", "Chhattisgarh"],
  ["Gaya", "Bihar"],
  ["Kurukshetra", "Haryana"],
  ["Theni", "Tamil Nadu"],
  ["Karur", "Tamil Nadu"],
  ["Kushinagar", "Uttar Pradesh"],
  ["Paschim Medinipur", "West Bengal"],
  ["Rewari", "Haryana"],
  ["Udham Singh Nagar", "Uttarakhand"],
  ["Kendrapara", "Odisha"],
  ["Bulandshahr", "Uttar Pradesh"],
  ["Hubli", "Karnataka"],
  ["Bara Banki", "Uttar Pradesh"],
  ["Bharuch", "Gujarat"],
  ["Navi Mumbai", "Maharashtra"],
  ["Thoothukkudi", "Tamil Nadu"],
  ["Navsari", "Gujarat"],
  ["Sindhudurg", "Maharashtra"],
  ["Hugli", "West Bengal"],
  ["Ratlam", "Madhya Pradesh"],
  ["Chikmagalur", "Karnataka"],
  ["Jorhat", "Assam"],
  ["Sambalpur", "Odisha"],
  ["Birbhum", "West Bengal"],
  ["Sant Kabir Nagar", "Uttar Pradesh"],
  ["Sehore", "Madhya Pradesh"],
  ["Bahraich", "Uttar Pradesh"],
  ["Hamirpur", "Himachal Pradesh"],
  ["Mansa", "Punjab"],
  ["Purba Medinipur", "West Bengal"],
  ["Kapurthala", "Punjab"],
  ["Nagercoil", "Tamil Nadu"],
  ["Dewas", "Madhya Pradesh"],
  ["Hoshangabad", "Madhya Pradesh"],
  ["Nagaon", "Assam"],
  ["Samastipur", "Bihar"],
  ["Bargarh", "Odisha"],
  ["Katni", "Madhya Pradesh"],
  ["Ramanathapuram", "Tamil Nadu"],
  ["Balangir", "Odisha"],
  ["Banas Kantha", "Gujarat"],
  ["Dhenkanal", "Odisha"],
  ["Raisen", "Madhya Pradesh"],
  ["Vaishali", "Bihar"],
  ["Pali", "Rajasthan"],
  ["Shivpuri", "Madhya Pradesh"],
  ["Baghpat", "Uttar Pradesh"],
  ["Greater Noida", "Uttar Pradesh"],
  ["Kachchh", "Gujarat"],
  ["Dimapur", "Nagaland"],
  ["Kheda", "Gujarat"],
  ["Madhubani", "Bihar"],
  ["Neemuch", "Madhya Pradesh"],
  ["Ahmednagar", "Maharashtra"],
  ["Barabanki", "Uttar Pradesh"],
  ["Damoh", "Madhya Pradesh"],
  ["Mandsaur", "Madhya Pradesh"],
  ["Ongole", "Andhra Pradesh"],
  ["Bhilwara", "Rajasthan"],
  ["Firozpur", "Punjab"],
  ["Mahrajganj", "Uttar Pradesh"],
  ["Panipat", "Haryana"],
  ["Berhampur", "Odisha"],
  ["Bhagalpur", "Bihar"],
  ["Hingoli", "Maharashtra"],
  ["Shahjahanpur", "Uttar Pradesh"],
  ["Surendranagar", "Gujarat"],
  ["Valsad", "Gujarat"],
  ["Bengaluru", "Karnataka"],
  ["Faridkot", "Punjab"],
  ["Fatehgarh Sahib", "Punjab"],
  ["Kakinada", "Andhra Pradesh"],
  ["Bhojpur", "Bihar"],
  ["Budaun", "Uttar Pradesh"],
  ["Mahendragarh", "Haryana"],
  ["Surguja", "Chhattisgarh"],
  ["Thiruvarur", "Tamil Nadu"],
  ["Una", "Himachal Pradesh"],
  ["Barnala", "Punjab"],
  ["Gondiya", "Maharashtra"],
  ["Haora", "West Bengal"],
  ["Janjgir - Champa", "Chhattisgarh"],
  ["Khargone", "Madhya Pradesh"],
  ["Sidhi", "Madhya Pradesh"],
  ["Jalpaiguri", "West Bengal"],
  ["Jyotiba Phule Nagar", "Uttar Pradesh"],
  ["North Goa", "Goa"],
  ["Rayagada", "Odisha"],
  ["Guna", "Madhya Pradesh"],
  ["Secunderabad", "Telangana"],
  ["Shahdol", "Madhya Pradesh"],
  ["Washim", "Maharashtra"],
  ["Burhanpur", "Madhya Pradesh"],
  ["Chikkaballapura", "Karnataka"],
  ["Kathua", "Jammu & Kashmir"],
  ["Korba", "Chhattisgarh"],
  ["Palwal", "Haryana"],
  ["South", "Delhi"],
  ["Aizawl", "Mizoram"],
  ["Datia", "Madhya Pradesh"],
  ["Dhar", "Madhya Pradesh"],
  ["Jajapur", "Odisha"],
  ["Seoni", "Madhya Pradesh"],
  ["Kheri", "Uttar Pradesh"],
  ["Kohima", "Nagaland"],
  ["Yamunanagar", "Haryana"],
  ["Balasore", "Odisha"],
  ["Bhilai", "Chhattisgarh"],
  ["Dibrugarh", "Assam"],
  ["Durgapur", "West Bengal"],
  ["Maldah", "West Bengal"],
  ["Nalanda", "Bihar"],
  ["Nayagarh", "Odisha"],
  ["Panna", "Madhya Pradesh"],
  ["Rampur", "Uttar Pradesh"],
  ["Wayanad", "Kerala"],
  ["West Tripura", "Tripura"],
  ["Jind", "Haryana"],
  ["Khandwa", "Madhya Pradesh"],
  ["Kendujhar", "Odisha"],
  ["Koraput", "Odisha"],
  ["Muktsar", "Punjab"],
  ["Nainital", "Uttarakhand"],
  ["Darjiling", "West Bengal"],
  ["Sawai Madhopur", "Rajasthan"],
  ["Yadgir", "Karnataka"],
  ["Ariyalur", "Tamil Nadu"],
  ["Dhamtari", "Chhattisgarh"],
  ["Dhaulpur", "Rajasthan"],
  ["Panchkula", "Haryana"],
  ["Rupnagar", "Punjab"],
  ["Trichy", "Tamil Nadu"],
  ["Anuppur", "Madhya Pradesh"],
  ["Barmer", "Rajasthan"],
  ["Chamarajanagar", "Karnataka"],
  ["Davangere", "Karnataka"],
  ["Kaithal", "Haryana"],
  ["Karad", "Maharashtra"],
  ["Roorkee", "Uttarakhand"],
  ["Sonbhadra", "Uttar Pradesh"],
  ["Chitrakoot", "Uttar Pradesh"],
  ["Dungarpur", "Rajasthan"],
  ["Lalitpur", "Uttar Pradesh"],
  ["Panch Mahals", "Gujarat"],
  ["Rajahmundry", "Andhra Pradesh"],
  ["Siddharthnagar", "Uttar Pradesh"],
  ["West", "Delhi"],
  ["Almora", "Uttarakhand"],
  ["Jhalawar", "Rajasthan"],
  ["Kodagu", "Karnataka"],
  ["Sirohi", "Rajasthan"],
  ["Siwan", "Bihar"],
  ["Chittaurgarh", "Rajasthan"],
  ["Karaikal", "Puducherry"],
  ["Madhepura", "Bihar"],
  ["Agartala", "Tripura"],
  ["Barpeta", "Assam"],
  ["Hatras", "Uttar Pradesh"],
  ["Kamrup Metropolitan", "Assam"],
  ["Purnia", "Bihar"],
  ["Puruliya", "West Bengal"],
  ["Saran", "Bihar"],
  ["Anugul", "Odisha"],
  ["Barwani", "Madhya Pradesh"],
  ["Kalahandi", "Odisha"],
  ["Lakhimpur", "Assam"],
  ["Maharajganj", "Uttar Pradesh"],
  ["Rajsamand", "Rajasthan"],
  ["Shajapur", "Madhya Pradesh"],
  ["Beed", "Maharashtra"],
  ["Berhampore", "West Bengal"],
  ["Buxar", "Bihar"],
  ["Dhemaji", "Assam"],
  ["East Khasi Hills", "Meghalaya"],
  ["Karauli", "Rajasthan"],
  ["Kochi", "Kerala"],
  ["Pathankot", "Punjab"],
  ["Tehri Garhwal", "Uttarakhand"],
  ["Villupuram", "Tamil Nadu"],
  ["Baran", "Rajasthan"],
  ["Bastar", "Chhattisgarh"],
  ["Begusarai", "Bihar"],
  ["Fatehabad", "Haryana"],
  ["Jhunjhunu", "Rajasthan"],
  ["Orai", "Uttar Pradesh"],
  ["Rourkela", "Odisha"],
  ["Sirmaur", "Himachal Pradesh"],
  ["Bokaro", "Jharkhand"],
  ["Nandyal", "Andhra Pradesh"],
  ["North West", "Delhi"],
  ["Singrauli", "Madhya Pradesh"],
  ["South Goa", "Goa"],
  ["Bundi", "Rajasthan"],
  ["Jharsuguda", "Odisha"],
  ["Katihar", "Bihar"],
  ["Malegaon", "Maharashtra"],
  ["Purbi Singhbhum", "Jharkhand"],
  ["Shahid Bhagat Singh Nagar", "Punjab"],
  ["Shillong", "Meghalaya"],
  ["Sitamarhi", "Bihar"],
  ["Balrampur", "Uttar Pradesh"],
  ["Dohad", "Gujarat"],
  ["Golaghat", "Assam"],
  ["Mohali", "Punjab"],
  ["Pilibhit", "Uttar Pradesh"],
  ["Dhubri", "Assam"],
  ["Imphal", "Manipur"],
  ["Narsimhapur", "Madhya Pradesh"],
  ["Raebareli", "Uttar Pradesh"],
  ["Sonepat", "Haryana"],
  ["Thoothukudi", "Tamil Nadu"],
  ["Cachar", "Assam"],
  ["Mahabubnagar", "Telangana"],
  ["Mahoba", "Uttar Pradesh"],
  ["Morbi", "Gujarat"],
  ["Porbandar", "Gujarat"],
  ["Saharsa", "Bihar"],
  ["Sivasagar", "Assam"],
  ["South West", "Delhi"],
  ["Suryapet", "Telangana"],
  ["Baramula", "Jammu & Kashmir"],
  ["Baripada", "Odisha"],
  ["Garhwa", "Jharkhand"],
  ["Garhwal", "Uttarakhand"],
  ["Hathras", "Uttar Pradesh"],
  ["Pithoragarh", "Uttarakhand"],
  ["Pulwama", "Jammu & Kashmir"],
  ["Puttur", "Andhra Pradesh"],
  ["Rajgarh", "Madhya Pradesh"],
  ["Sant Ravidas Nagar (bhadohi)", "Uttar Pradesh"],
  ["Tarn Taran", "Punjab"],
  ["Tikamgarh", "Madhya Pradesh"],
  ["Harda", "Madhya Pradesh"],
  ["Jagatsinghapur", "Odisha"],
  ["Kokrajhar", "Assam"],
  ["Sri Ganganagar", "Rajasthan"],
  ["Central", "Delhi"],
  ["Proddatur", "Andhra Pradesh"],
  ["Shikohabad", "Uttar Pradesh"],
  ["Amethi", "Uttar Pradesh"],
  ["Burdwan", "West Bengal"],
  ["Chamba", "Himachal Pradesh"],
  ["Chamoli", "Uttarakhand"],
  ["Haridwar", "Uttarakhand"],
  ["Jashpur", "Chhattisgarh"],
  ["Kandhamal", "Odisha"],
  ["Sangamner", "Maharashtra"],
  ["Sonitpur", "Assam"],
  ["Ambikapur", "Chhattisgarh"],
  ["Botad", "Gujarat"],
  ["Calicut", "Kerala"],
  ["Eluru", "Andhra Pradesh"],
  ["Koch Bihar", "West Bengal"],
  ["Palamu", "Jharkhand"],
  ["East", "Sikkim"],
  ["Hanamkonda", "Telangana"],
  ["Malda", "West Bengal"],
  ["Tadepalligudem", "Andhra Pradesh"],
  ["Tinsukia", "Assam"],
  ["Baramati", "Maharashtra"],
  ["Chomu", "Rajasthan"],
  ["Dumka", "Jharkhand"],
  ["Giridih", "Jharkhand"],
  ["Jamshedpur", "Jharkhand"],
  ["Kishanganj", "Bihar"],
  ["Kullu", "Himachal Pradesh"],
  ["Mahasamund", "Chhattisgarh"],
  ["Mandla", "Madhya Pradesh"],
  ["Ramgarh", "Jharkhand"],
  ["Anantnag", "Jammu & Kashmir"],
  ["Bhimavaram", "Andhra Pradesh"],
  ["Deoghar", "Jharkhand"],
  ["Himatnagar", "Gujarat"],
  ["Kodad", "Telangana"],
  ["Narasaraopet", "Andhra Pradesh"],
  ["Behror", "Rajasthan"],
  ["Budgam", "Jammu & Kashmir"],
  ["Dakshin Dinajpur", "West Bengal"],
  ["Dholpur", "Rajasthan"],
  ["Haldia", "West Bengal"],
  ["Hapur", "Uttar Pradesh"],
  ["Imphal West", "Manipur"],
  ["Markapur", "Andhra Pradesh"],
  ["Modinagar", "Uttar Pradesh"],
  ["Nalbari", "Assam"],
  ["Nuapada", "Odisha"],
  ["Pandharpur", "Maharashtra"],
  ["Silchar", "Assam"],
  ["Tenali", "Andhra Pradesh"],
  ["Thodupuzha", "Kerala"],
  ["Udhampur", "Jammu & Kashmir"],
  ["Akbarpur", "Uttar Pradesh"],
  ["Angul", "Odisha"],
  ["Ashoknagar", "Madhya Pradesh"],
  ["Bahadurgarh", "Haryana"],
  ["Belagavi", "Karnataka"],
  ["Bongaigaon", "Assam"],
  ["Chikodi", "Karnataka"],
  ["Gondia", "Maharashtra"],
  ["Gopalganj", "Bihar"],
  ["Jagdalpur", "Chhattisgarh"],
  ["Jajpur", "Odisha"],
  ["Kanchipuram", "Tamil Nadu"],
  ["Koriya", "Chhattisgarh"],
  ["Mahendergarh", "Haryana"],
  ["North", "Delhi"],
  ["Perinthalmanna", "Kerala"],
  ["Sheopur", "Madhya Pradesh"],
  ["Amroha", "Uttar Pradesh"],
  ["Hazaribagh", "Jharkhand"],
  ["Imphal East", "Manipur"],
  ["Kotputli", "Rajasthan"],
  ["Madanapalle", "Andhra Pradesh"],
  ["Mehsana", "Gujarat"],
  ["Nawada", "Bihar"],
  ["Palanpur", "Gujarat"],
  ["Rajouri", "Jammu & Kashmir"],
  ["Siliguri", "West Bengal"],
  ["Tirupur", "Tamil Nadu"],
  ["Ambajogai", "Maharashtra"],
  ["Araria", "Bihar"],
  ["Champawat", "Uttarakhand"],
  ["Chapra", "Bihar"],
  ["Haldwani", "Uttarakhand"],
  ["Howrah", "West Bengal"],
  ["Ibrahimpatnam", "Telangana"],
  ["Keonjhar", "Odisha"],
  ["Kharar", "Punjab"],
  ["Noida", "Uttar Pradesh"],
  ["Phagwara", "Punjab"],
  ["Purulia", "West Bengal"],
  ["Rudraprayag", "Uttarakhand"],
  ["Samba", "Jammu & Kashmir"],
  ["Siddipet", "Telangana"],
  ["Tirupathi", "Andhra Pradesh"],
  ["Udgir", "Maharashtra"],
  ["Umaria", "Madhya Pradesh"],
  ["Abohar", "Punjab"],
  ["Asansol", "West Bengal"],
  ["Bhadra", "Rajasthan"],
  ["Bhawanipatna", "Odisha"],
  ["Bhongir", "Telangana"],
  ["Chirala", "Andhra Pradesh"],
  ["Fazilka", "Punjab"],
  ["Gangtok", "Sikkim"],
  ["Kalyani", "West Bengal"],
  ["Khagaria", "Bihar"],
  ["Kumbakonam", "Tamil Nadu"],
  ["Lalsot", "Rajasthan"],
  ["Machilipatnam", "Andhra Pradesh"],
  ["Mewat", "Haryana"],
  ["Miraj", "Maharashtra"],
  ["Morigaon", "Assam"],
  ["Munger", "Bihar"],
  ["Subarnapur", "Odisha"],
  ["Tanuku", "Andhra Pradesh"],
  ["Uttarkashi", "Uttarakhand"],
  ["Chiplun", "Maharashtra"],
  ["Gadhinglaj", "Maharashtra"],
  ["Gir Somnath", "Gujarat"],
  ["Goalpara", "Assam"],
  ["Jalor", "Rajasthan"],
  ["Jehanabad", "Bihar"],
  ["Jhabua", "Madhya Pradesh"],
  ["Kaimur (bhabua)", "Bihar"],
  ["Karimganj", "Assam"],
  ["Manipal", "Karnataka"],
  ["Nawalgarh", "Rajasthan"],
  ["Rajpura", "Punjab"],
  ["Sivakasi", "Tamil Nadu"],
  ["Ulhasnagar", "Maharashtra"],
  ["Vinukonda", "Andhra Pradesh"],
  ["Visnagar", "Gujarat"],
  ["Yamuna Nagar", "Haryana"],
  ["Ahmedpur", "Maharashtra"],
  ["Ashti", "Maharashtra"],
  ["Bageshwar", "Uttarakhand"],
  ["Banka", "Bihar"],
  ["Batala", "Punjab"],
  ["Bhiwandi", "Maharashtra"],
  ["Dahod", "Gujarat"],
  ["Ganderbal", "Jammu & Kashmir"],
  ["Gohana", "Haryana"],
  ["Humnabad", "Karnataka"],
  ["Kanshiram Nagar", "Uttar Pradesh"],
  ["Karwar", "Karnataka"],
  ["Komarapalayam", "Tamil Nadu"],
  ["Krishnagar", "West Bengal"],
  ["Mokokchung", "Nagaland"],
  ["Narmada", "Gujarat"],
  ["Neem Ka Thana", "Rajasthan"],
  ["Pilani", "Rajasthan"],
  ["Pollachi", "Tamil Nadu"],
  ["Rawatsar", "Rajasthan"],
  ["Rudrapur", "Uttarakhand"],
  ["Sindhanur", "Karnataka"],
  ["Supaul", "Bihar"],
  ["Tapi", "Gujarat"],
  ["Thiruvalla", "Kerala"],
  ["Tiruchengode", "Tamil Nadu"],
  ["Athani", "Karnataka"],
  ["Bapatla", "Andhra Pradesh"],
  ["Barshi", "Maharashtra"],
  ["Basavakalyan", "Karnataka"],
  ["Bramhapuri", "Maharashtra"],
  ["Cherthala", "Kerala"],
  ["Cumbum", "Andhra Pradesh"],
  ["Hailakandi", "Assam"],
  ["Islampur", "Maharashtra"],
  ["Kalyan", "Maharashtra"],
  ["Khalilabad", "Uttar Pradesh"],
  ["Mahe", "Puducherry"],
  ["Marthandam", "Tamil Nadu"],
  ["Pusad", "Maharashtra"],
  ["Rayachoty", "Andhra Pradesh"],
  ["Robertsganj", "Uttar Pradesh"],
  ["Sangareddy", "Telangana"],
  ["Shirpur", "Maharashtra"],
  ["The Nilgiris", "Tamil Nadu"],
  ["Tirupattur", "Tamil Nadu"],
  ["Trivandrum", "Kerala"],
  ["Uttar Bastar Kanker", "Chhattisgarh"],
  ["Uttar Dinajpur", "West Bengal"],
  ["Amalapuram", "Andhra Pradesh"],
  ["Ambedkarnagar", "Uttar Pradesh"],
  ["Ara", "Bihar"],
  ["Bangalore Urban", "Karnataka"],
  ["Bhatkal", "Karnataka"],
  ["Bhuj", "Gujarat"],
  ["Bobbili", "Andhra Pradesh"],
  ["Chirawa", "Rajasthan"],
  ["Darsi", "Andhra Pradesh"],
  ["Dindori", "Madhya Pradesh"],
  ["Gajapati", "Odisha"],
  ["Godhra", "Gujarat"],
  ["Hazaribag", "Jharkhand"],
  ["Hindupur", "Andhra Pradesh"],
  ["Jagatsinghpur", "Odisha"],
  ["Jangaon", "Telangana"],
  ["Kabeerdham", "Chhattisgarh"],
  ["Kalol", "Gujarat"],
  ["Kanhangad", "Kerala"],
  ["Karaikudi", "Tamil Nadu"],
  ["Kasganj", "Uttar Pradesh"],
  ["Kopargaon", "Maharashtra"],
  ["Kothamangalam", "Kerala"],
  ["Lehragaga", "Punjab"],
  ["Mancherial", "Telangana"],
  ["Midnapore", "West Bengal"],
  ["Moodbidri", "Karnataka"],
  ["Newasa", "Maharashtra"],
  ["Nuzvid", "Andhra Pradesh"],
  ["Ranebennur", "Karnataka"],
  ["Ranga Reddy", "Telangana"],
  ["Shahada", "Maharashtra"],
  ["Shrawasti", "Uttar Pradesh"],
  ["Adoor", "Kerala"],
  ["Akluj", "Maharashtra"],
  ["Armori", "Maharashtra"],
  ["Chidambaram", "Tamil Nadu"],
  ["Daman", "Dadra & Nagar Haveli and Daman & Diu"],
  ["Dhampur", "Uttar Pradesh"],
  ["Dharapuram", "Tamil Nadu"],
  ["Gokak", "Karnataka"],
  ["Hooghly", "West Bengal"],
  ["Janjgir", "Chhattisgarh"],
  ["Jasrana", "Uttar Pradesh"],
  ["Kadiri", "Andhra Pradesh"],
  ["Lunglei", "Mizoram"],
  ["Muvattupuzha", "Kerala"],
  ["Nabarangapur", "Odisha"],
  ["Narnaul", "Haryana"],
  ["Narsinghpur", "Madhya Pradesh"],
  ["Nohar", "Rajasthan"],
  ["Ponda", "Goa"],
  ["Sangola", "Maharashtra"],
  ["Shamli", "Uttar Pradesh"],
  ["Tezpur", "Assam"],
  ["Vikarabad", "Telangana"],
  ["Wanaparthy", "Telangana"],
  ["Yeola", "Maharashtra"],
  ["Aluva", "Kerala"],
  ["Amalner", "Maharashtra"],
  ["Anantapuramu", "Andhra Pradesh"],
  ["Balod", "Chhattisgarh"],
  ["Bangarpet", "Karnataka"],
  ["Barasat", "West Bengal"],
  ["Bhalki", "Karnataka"],
  ["Bodhan", "Telangana"],
  ["Chalisgaon", "Maharashtra"],
  ["Chinsurah", "West Bengal"],
  ["Ferozepur", "Punjab"],
  ["Godavarikhani", "Telangana"],
  ["Godda", "Jharkhand"],
  ["Hajipur", "Bihar"],
  ["Jagtial", "Telangana"],
  ["Jaisalmer", "Rajasthan"],
  ["Jeypore", "Odisha"],
  ["Kallakurichi", "Tamil Nadu"],
  ["Kashipur", "Uttarakhand"],
  ["Katol", "Maharashtra"],
  ["Kavali", "Andhra Pradesh"],
  ["Khed", "Maharashtra"],
  ["Kothagudem", "Telangana"],
  ["Kudal", "Maharashtra"],
  ["Laxmangarh", "Rajasthan"],
  ["Lingasugur", "Karnataka"],
  ["Mandi Gobindgarh", "Punjab"],
  ["Manjeri", "Kerala"],
  ["Modasa", "Gujarat"],
  ["Mysuru", "Karnataka"],
  ["Pala", "Kerala"],
  ["Panaji", "Goa"],
  ["Panvel", "Maharashtra"],
  ["Phulbani", "Odisha"],
  ["Podili", "Andhra Pradesh"],
  ["Purnea", "Bihar"],
  ["Reasi", "Jammu & Kashmir"],
  ["Rishikesh", "Uttarakhand"],
  ["Sheikhpura", "Bihar"],
  ["Sirsi", "Karnataka"],
  ["Sopore", "Jammu & Kashmir"],
  ["Tanda", "Uttar Pradesh"],
  ["Vallabh Vidyanagar", "Gujarat"],
  ["Alibag", "Maharashtra"],
  ["Armoor", "Telangana"],
  ["Baraut", "Uttar Pradesh"],
  ["Bokaro Steel City", "Jharkhand"],
  ["Dakshin Bastar Dantewada", "Chhattisgarh"],
  ["Darrang", "Assam"],
  ["Debagarh", "Odisha"],
  ["Guntakal", "Andhra Pradesh"],
  ["Himmatnagar", "Gujarat"],
  ["Hindaun City", "Rajasthan"],
  ["Itarsi", "Madhya Pradesh"],
  ["Jamui", "Bihar"],
  ["Jayankondam", "Tamil Nadu"],
  ["Kadi", "Gujarat"],
  ["Kamareddy", "Telangana"],
  ["Karbi Anglong", "Assam"],
  ["Karjat", "Maharashtra"],
  ["Kupwara", "Jammu & Kashmir"],
  ["Lakhisarai", "Bihar"],
  ["Malerkotla", "Punjab"],
  ["Malkangiri", "Odisha"],
  ["Malout", "Punjab"],
  ["Mangaluru", "Karnataka"],
  ["Padampur", "Rajasthan"],
  ["Palamaner", "Andhra Pradesh"],
  ["Paloncha", "Telangana"],
  ["Papum Pare", "Arunachal Pradesh"],
  ["Perumbavoor", "Kerala"],
  ["Phaltan", "Maharashtra"],
  ["Raikot", "Punjab"],
  ["Sankeshwar", "Karnataka"],
  ["Shivamogga", "Karnataka"],
  ["Suri", "West Bengal"],
  ["Taranagar", "Rajasthan"],
  ["Thoubal", "Manipur"],
  ["Vita", "Maharashtra"],
  ["Adoni", "Andhra Pradesh"],
  ["Akkalkuwa", "Maharashtra"],
  ["Ananthapuramu", "Andhra Pradesh"],
  ["Aravalli", "Gujarat"],
  ["Ausa", "Maharashtra"],
  ["Bandipore", "Jammu & Kashmir"],
  ["Bansur", "Rajasthan"],
  ["Baramulla", "Jammu & Kashmir"],
  ["Bhadravathi", "Karnataka"],
  ["Bhusawal", "Maharashtra"],
  ["Bissau", "Rajasthan"],
  ["Bolangir", "Odisha"],
  ["Chengalpattu", "Tamil Nadu"],
  ["Chhibramau", "Uttar Pradesh"],
  ["Chickballapur", "Karnataka"],
  ["Chintamani", "Karnataka"],
  ["Chittorgarh", "Rajasthan"],
  ["Contai", "West Bengal"],
  ["Devarakonda", "Telangana"],
  ["Domkal", "West Bengal"],
  ["Ghatkesar", "Telangana"],
  ["Giddalur", "Andhra Pradesh"],
  ["Ichalkaranji", "Maharashtra"],
  ["Ilkal", "Karnataka"],
  ["Indi", "Karnataka"],
  ["Kaij", "Maharashtra"],
  ["Kandukur", "Andhra Pradesh"],
  ["Khetri", "Rajasthan"],
  ["Kodinar", "Gujarat"],
  ["Kotkapura", "Punjab"],
  ["Loni", "Maharashtra"],
  ["Miryalaguda", "Telangana"],
  ["Narsipatnam", "Andhra Pradesh"],
  ["Nathdwara", "Rajasthan"],
  ["Neemkathana", "Rajasthan"],
  ["Nirmal", "Telangana"],
  ["Nurpur", "Himachal Pradesh"],
  ["Palani", "Tamil Nadu"],
  ["Paramakudi", "Tamil Nadu"],
  ["Pashchim Champaran", "Bihar"],
  ["Pashchimi Singhbhum", "Jharkhand"],
  ["Peddapuram", "Andhra Pradesh"],
  ["Prantij", "Gujarat"],
  ["Rajampet", "Andhra Pradesh"],
  ["Rajapalayam", "Tamil Nadu"],
  ["Rajura", "Maharashtra"],
  ["Rasra", "Uttar Pradesh"],
  ["Sakoli", "Maharashtra"],
  ["Sankarankovil", "Tamil Nadu"],
  ["Shrimadhopur", "Rajasthan"],
  ["Singarayakonda", "Andhra Pradesh"],
  ["Tadipatri", "Andhra Pradesh"],
  ["Tuni", "Andhra Pradesh"],
  ["Bemetara", "Chhattisgarh"],
  ["Bishnupur", "Manipur"],
  ["Dadra & Nagar Haveli", "Dadra & Nagar Haveli and Daman & Diu"],
  ["Doda", "Jammu & Kashmir"],
  ["Jamtara", "Jharkhand"],
  ["Kishtwar", "Jammu & Kashmir"],
  ["Kodarma", "Jharkhand"],
  ["Mungeli", "Chhattisgarh"],
  ["Palghar", "Maharashtra"],
  ["Panchsheel Nagar", "Uttar Pradesh"],
  ["Purba Champaran", "Bihar"],
  ["Arwal", "Bihar"],
  ["Chatra", "Jharkhand"],
  ["Chatrapati Shuji Maharaj Nagar", "Uttar Pradesh"],
  ["Churachandpur", "Manipur"],
  ["Gariaband", "Chhattisgarh"],
  ["Gumla", "Jharkhand"],
  ["Lohardaga", "Jharkhand"],
  ["Mahisagar", "Gujarat"],
  ["Saraikela-Kharsawan", "Jharkhand"],
  ["Senapati", "Manipur"],
  ["The Dangs", "Gujarat"],
  ["Udalguri", "Assam"],
  ["West Garo Hills", "Meghalaya"],
  ["Alirajpur", "Madhya Pradesh"],
  ["Baudh", "Odisha"],
  ["Kulgam", "Jammu & Kashmir"],
  ["North Tripura", "Tripura"],
  ["Punch", "Jammu & Kashmir"],
  ["Ramban", "Jammu & Kashmir"],
  ["South Tripura", "Tripura"],
  ["Yanam", "Puducherry"],
  ["Baksa", "Assam"],
  ["Dhalai", "Tripura"],
  ["Kinnaur", "Himachal Pradesh"],
  ["Lower Subansiri", "Arunachal Pradesh"],
  ["Sahibganj", "Jharkhand"],
  ["Champhai", "Mizoram"],
  ["Chhota Udepur", "Gujarat"],
  ["Chirang", "Assam"],
  ["Diu", "Dadra & Nagar Haveli and Daman & Diu"],
  ["Kargil", "Jammu & Kashmir"],
  ["Latehar", "Jharkhand"],
  ["Mamit", "Mizoram"],
  ["Narayanpur", "Chhattisgarh"],
  ["Nicobars", "Andaman & Nicobar Islands"],
  ["North East", "Delhi"],
  ["Serchhip", "Mizoram"],
  ["Sheohar", "Bihar"],
  ["Shupiyan", "Jammu & Kashmir"],
  ["Surajpur", "Chhattisgarh"],
  ["Tuensang", "Nagaland"],
  ["West Khasi Hills", "Meghalaya"],
  ["Amaravati", "Andhra Pradesh"],
  ["Baloda Bazar", "Chhattisgarh"],
  ["Chandel", "Manipur"],
  ["East Jaintia Hills", "Meghalaya"],
  ["East Siang", "Arunachal Pradesh"],
  ["Khunti", "Jharkhand"],
  ["Kondagaon", "Chhattisgarh"],
  ["Lakshadweep", "Lakshadweep"],
  ["Lawngtlai", "Mizoram"],
  ["Pakur", "Jharkhand"],
  ["Peren", "Nagaland"],
  ["Ribhoi", "Meghalaya"],
  ["Saiha", "Mizoram"],
  ["Wokha", "Nagaland"],
  ["Zunheboto", "Nagaland"],
  ["Kolasib", "Mizoram"],
  ["Lahul & Spiti", "Himachal Pradesh"],
  ["Lohit", "Arunachal Pradesh"],
  ["Mon", "Nagaland"],
  ["Phek", "Nagaland"],
  ["West Jaintia Hills", "Meghalaya"],
  ["Bhim Nagar", "Uttar Pradesh"],
  ["Changlang", "Arunachal Pradesh"],
  ["Devbhoomi Dwarka", "Gujarat"],
  ["Dima Hasao", "Assam"],
  ["Kiphire", "Nagaland"],
  ["Leh(ladakh)", "Jammu & Kashmir"],
  ["Longleng", "Nagaland"],
  ["Mumbai City", "Maharashtra"],
  ["Prabuddh Nagar", "Uttar Pradesh"],
  ["Rangareddi", "Telangana"],
  ["South Andaman", "Andaman & Nicobar Islands"],
  ["Tamenglong", "Manipur"],
  ["Ukhrul", "Manipur"],
  ["Unakoti", "Tripura"],
  ["West Kameng", "Arunachal Pradesh"],
  ["East Garo Hills", "Meghalaya"],
  ["Gomati", "Tripura"],
  ["Kurung Kumey", "Arunachal Pradesh"],
  ["North & Middle Andaman", "Andaman & Nicobar Islands"],
  ["North Garo Hills", "Meghalaya"],
  ["South West Delhi", "Delhi"],
  ["Upper Subansiri", "Arunachal Pradesh"],
  ["West Siang", "Arunachal Pradesh"],
];

export const STATE_NAMES: readonly string[] = [
  "Andaman & Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra & Nagar Haveli and Daman & Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu & Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];
